"""Build scripts/font-common-chars.txt, the characters of the on-demand font
extension (scripts/build-maanshan-fonts.py), from the Unicode Unihan database.

Text the platform does not ship itself (AI replies, speech-to-text results,
pupils' and teachers' names, server messages) can hold any character. The
subset fonts carry only the characters of the platform's own files; the
extension slices carry the common rest, so that text stays in one font too.

    python scripts/build-font-common-chars.py path/to/Unihan.zip

The list holds, in this order:
  symbols      punctuation and symbols of Chinese text (first line), the
               common punctuation first
  traditional  Big5 level 1 (kBigFive A440-C67E, the 5401 common characters),
               the Hong Kong list of graphemes of commonly used characters
               (kHKGlyph), the Hong Kong primary school grades 1-6 (kGradeLevel)
               and the Cantonese characters listed in CANTONESE below
  simplified   GB 2312 level 1 (kGB0 1601-5589) not in the set above, for text
               that arrives in simplified Chinese
Within each group: kHanyuPinlu frequency (a traditional character takes the
frequency of its simplified form), then kGradeLevel, then code point. The
extension build cuts the list into slices in this order, so ordinary
Traditional Chinese text needs only the first few slices and never a
simplified one.
"""
import io
import sys
import zipfile
from pathlib import Path

OUTPUT = Path(__file__).resolve().parent / 'font-common-chars.txt'
# Punctuation and symbols that Chinese text uses. The build keeps those the
# Hong Kong fonts have.
SYMBOLS = [(0x3000, 0x303F), (0xFF01, 0xFF60), (0xFFE0, 0xFFE6), (0x2010, 0x2027), (0x2030, 0x203B),
           (0xFE30, 0xFE4F), (0xFE50, 0xFE6B), (0x2103, 0x2103), (0x2116, 0x2116), (0x2121, 0x2122),
           (0x2160, 0x217F), (0x2190, 0x2199), (0x221A, 0x221A), (0x221E, 0x221E), (0x2220, 0x2220),
           (0x2234, 0x2235), (0x2248, 0x2248), (0x2260, 0x2261), (0x2264, 0x2265), (0x2460, 0x249B), (0x25A0, 0x25FF),
           (0x2605, 0x2606), (0x2609, 0x2609), (0x260E, 0x260F), (0x2640, 0x2642), (0x266A, 0x266F),
           (0x3105, 0x312F), (0x3220, 0x3243), (0x3280, 0x32B0)]
# Common Cantonese characters of everyday written Cantonese (not in Big5 level
# 1), so a reply or a name that uses them keeps the Hong Kong design.
CANTONESE = ('佢嘅咗啲冇嚟喺哋嘢咁噉乜啱嗰咩喎囉嘞㗎嘛吖啦喇喂嗱咪搵睇諗攞畀俾嘥唔係靚餸瞓掂咋噃啩吓嘈撳揸'
             '郁攰嚇嗌啫埋冚喐瞌噏啖嚿枱櫈甩囡孖冧氹凼嘟嚤嗮咭啜嗒嚡揼揦捽')


def fields(archive, wanted):
    data = {name: {} for name in wanted}
    with zipfile.ZipFile(archive) as bundle:
        for member in bundle.namelist():
            if not member.endswith('.txt'):
                continue
            with bundle.open(member) as raw:
                for line in io.TextIOWrapper(raw, encoding='utf-8'):
                    if line.startswith('#') or '\t' not in line:
                        continue
                    code, field, value = line.rstrip('\n').split('\t')
                    if field in data:
                        data[field][int(code[2:], 16)] = value
    return data


def code_points(value):
    return [int(token[2:].split('<')[0], 16) for token in value.split() if token.startswith('U+')]


def main(archive):
    data = fields(archive, ('kBigFive', 'kHKGlyph', 'kGradeLevel', 'kGB0', 'kHanyuPinlu', 'kSimplifiedVariant'))
    big5 = {code for code, value in data['kBigFive'].items() if 0xA440 <= int(value.rstrip("'"), 16) <= 0xC67E}
    gb = {code for code, value in data['kGB0'].items() if 1601 <= int(value) <= 5589}
    grade = {code: int(value) for code, value in data['kGradeLevel'].items()}
    traditional = big5 | set(data['kHKGlyph']) | set(grade) | {ord(ch) for ch in CANTONESE}
    simplified = gb - traditional

    def count(code):
        value = data['kHanyuPinlu'].get(code, '')
        return sum(int(part.split('(')[1].rstrip(')')) for part in value.split() if '(' in part)

    frequency = {code: count(code) for code in traditional | simplified}
    for code in traditional:
        for simple in code_points(data['kSimplifiedVariant'].get(code, '')):
            frequency[code] = max(frequency[code], count(simple))
    key = lambda code: (-frequency[code], grade.get(code, 9), code)
    order = sorted(traditional, key=key) + sorted(simplified, key=key)
    symbols = ''.join(chr(code) for low, high in SYMBOLS for code in range(low, high + 1))
    han = ''.join(map(chr, order))
    lines = [han[i:i + 50] for i in range(0, len(han), 50)]
    header = [
        '# Characters of the on-demand font extension: symbols, then traditional, then simplified, each most',
        '# frequent first. Generated by scripts/build-font-common-chars.py from the Unicode Unihan database',
        '# (Unicode 18.0, Unihan.zip of 2026-07-31: kBigFive, kHKGlyph, kGradeLevel, kGB0, kHanyuPinlu,',
        '# kSimplifiedVariant).',
        '# Copyright (c) 1991-2026 Unicode, Inc. Unicode License v3, https://www.unicode.org/license.txt',
        f'# {len(symbols)} symbols (first line), {len(traditional)} traditional and {len(simplified)} simplified characters.',
    ]
    OUTPUT.write_text('\n'.join(header + [symbols] + lines) + '\n', encoding='utf-8', newline='\n')
    print(f'{len(symbols)} symbols, {len(traditional)} traditional, {len(simplified)} simplified -> {OUTPUT}')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
