"""Publish full-resolution JPEG/PNG alternatives, independent of COS and WebP."""
from pathlib import Path
import hashlib
import json
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
manifest = json.loads((ROOT / 'deploy/media-manifest.json').read_text('utf-8'))
paths = {a['source'].lstrip('/') for a in manifest['assets'] if a['contentType'] == 'image/webp'}
for directory in ['poem-games', 'challenges', 'living-scenes', 'exploration']:
    paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT / 'maanshan/media' / directory).rglob('*.webp'))
paths.add('maanshan/media/shishi/guide-still-20260919a.webp')
output = ROOT / 'maanshan/media/compatible'
output.mkdir(exist_ok=True)
mapping = {}
for relative in sorted(paths):
    source = ROOT / relative
    with Image.open(source) as image:
        image.load()
        alpha = 'A' in image.getbands() and image.getchannel('A').getextrema()[0] < 255
        suffix = '.png' if alpha else '.jpg'
        digest = hashlib.sha256(source.read_bytes() + b'jpeg88-444-png-v1').hexdigest()[:20]
        target = output / (digest + suffix)
        if alpha:
            image.save(target, 'PNG', optimize=True)
        else:
            image.convert('RGB').save(target, 'JPEG', quality=88, subsampling=0, optimize=True, progressive=True)
        mapping['/' + relative] = '/' + target.relative_to(ROOT).as_posix()
(ROOT / 'maanshan/image-compat.mjs').write_text(
    '// Generated by scripts/build-image-compat.py. Full-resolution public artwork.\n'
    + 'export const COMPAT_IMAGES = Object.freeze(' + json.dumps(mapping, indent=2) + ');\n', 'utf-8')
print(json.dumps({'images': len(mapping), 'bytes': sum((ROOT / p.lstrip('/')).stat().st_size for p in mapping.values())}))
