// Generated by deploy/media_config.py --write. Public 3D model copies only.
export const MODEL_ASSETS = Object.freeze({
  "/maanshan/media/exploration/bo-chuan-gua-zhou/model-20260919b.glb": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/2ea7d5ebb933becacdb4/maanshan/media/exploration/bo-chuan-gua-zhou/model-20260919b.glb",
  "/maanshan/media/exploration/bo-chuan-gua-zhou/model.glb": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/9440463a264bed81217c/maanshan/media/exploration/bo-chuan-gua-zhou/model.glb",
  "/maanshan/media/exploration/gui-yuan-tian-ju/model-20260920a.glb": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/8314aa1050f459812960/maanshan/media/exploration/gui-yuan-tian-ju/model-20260920a.glb",
  "/maanshan/media/exploration/gui-yuan-tian-ju/model.glb": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/9dd9f6ffc2f62a3452a2/maanshan/media/exploration/gui-yuan-tian-ju/model.glb",
  "/maanshan/media/exploration/jue-ju/model-20261005.glb": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/8cbd250cedaee29ece33/maanshan/media/exploration/jue-ju/model-20261005.glb",
  "/maanshan/media/exploration/ke-zhi/model-20261005.glb": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/61c12af1504d6da6619d/maanshan/media/exploration/ke-zhi/model-20261005.glb",
  "/maanshan/media/exploration/ti-xi-lin-bi/model.glb": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/fa9753ea598a3522da9b/maanshan/media/exploration/ti-xi-lin-bi/model.glb",
  "/maanshan/media/exploration/zao-chun/model-20260919b.glb": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/d026e39e93b3b8000955/maanshan/media/exploration/zao-chun/model-20260919b.glb",
  "/maanshan/media/exploration/zao-chun/model.glb": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/cd6ff9a12978705b44b3/maanshan/media/exploration/zao-chun/model.glb",
  "/maanshan/media/exploration/zheng-ren-mai-lu/model-20261005.glb": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/adcaaf9a72b6c3693f7a/maanshan/media/exploration/zheng-ren-mai-lu/model-20261005.glb",
  "/maanshan/media/living-scenes/bean-v1.glb": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/4e819ae9a9782074c7ab/maanshan/media/living-scenes/bean-v1.glb",
  "/maanshan/media/living-scenes/grass-v1.glb": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/27224c03954d1ed4ef54/maanshan/media/living-scenes/grass-v1.glb"
});
