// Generated by deploy/media_config.py --write. Public font copies only.
export const FONT_ASSETS = Object.freeze({
  "/maanshan/vendor/fonts/noto-sans-tc-variants.woff2": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/8618256cfb6f22d7e70e/maanshan/vendor/fonts/noto-sans-tc-variants.woff2",
  "/maanshan/vendor/fonts/noto-sans-tc.woff2": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/7ce4f70d4de7850d814f/maanshan/vendor/fonts/noto-sans-tc.woff2",
  "/maanshan/vendor/fonts/noto-serif-tc-variants.woff2": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/7e01461e5006ede780c3/maanshan/vendor/fonts/noto-serif-tc-variants.woff2",
  "/maanshan/vendor/fonts/noto-serif-tc.woff2": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/a0c9b7af5e1d0ab4bce5/maanshan/vendor/fonts/noto-serif-tc.woff2"
});
