// Generated by deploy/media_config.py --write. Public recorded audio folders only.
export const AUDIO_GROUPS = Object.freeze({
  "/maanshan/media/recitations/edb-20260921/": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/g-5c6c7570d77901714d8b/maanshan/media/recitations/edb-20260921/",
  "/maanshan/media/speech/": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/g-2066b9e2c02b942ab9a0/maanshan/media/speech/",
  "/maanshan/media/words/": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/g-9181908b9a88540cf3bd/maanshan/media/words/"
});
