// Generated by deploy/media_config.py --write. Public font copies only.
export const FONT_ASSETS = Object.freeze({
  "/maanshan/vendor/fonts/noto-sans-hk-variants.woff2": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/38f517e51a8a25aff1e3/maanshan/vendor/fonts/noto-sans-hk-variants.woff2",
  "/maanshan/vendor/fonts/noto-sans-hk.woff2": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/1dfcba192871af35da75/maanshan/vendor/fonts/noto-sans-hk.woff2",
  "/maanshan/vendor/fonts/noto-serif-hk-variants.woff2": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/a9e02af4d66dfc7ef15d/maanshan/vendor/fonts/noto-serif-hk-variants.woff2",
  "/maanshan/vendor/fonts/noto-serif-hk.woff2": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/3de831b6e9955fdd9e28/maanshan/vendor/fonts/noto-serif-hk.woff2",
  "/maanshan/vendor/fonts/school-pinyin-400.woff2": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/4c0dc07e58072e53a42e/maanshan/vendor/fonts/school-pinyin-400.woff2",
  "/maanshan/vendor/fonts/school-pinyin-700.woff2": "https://aiducation-mandarin-media-1427410149.cos.ap-guangzhou.myqcloud.com/published/0db66e6e94fc64984d0b/maanshan/vendor/fonts/school-pinyin-700.woff2"
});
